services:
  arch: 
    build:
      context: .
      dockerfile: Dockerfile

    
    image: lazy-arch
    container_name: LazyArch

    tty: true
    stdin_open: true
      
    restart: unless-stopped
  
