use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use dialoguer::{Input, Password, Select};
use crate::features::docker;
use crate::system::{pacman_install, sudo};
use crate::ui;

const CONTAINER: &str = "lazyarch-windows";

fn dir() -> PathBuf {
    let home = std::env::var("HOME").expect("HOME not set");
    Path::new(&home).join(".local/share/lazyarch/windows")
}

pub fn done() -> bool {
    dir().join("compose.yml").exists()
}

/// Single-quotes a value for a shell script.
fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

fn write_private(path: &Path, content: &str, mode: u32) {
    fs::write(path, content).expect("Failed to write file");
    fs::set_permissions(path, fs::Permissions::from_mode(mode)).expect("Failed to set permissions");
}

fn compose_yaml(version: &str, language: &str, cores: u32, ram: u32, disk: u32, username: &str, password: &str) -> String {
    // Ports bound to 127.0.0.1 only, so the VM isn't reachable from the network.
    // {:?} gives double-quoted, escaped strings that YAML accepts.
    format!(
        r#"services:
  windows:
    image: dockurr/windows
    container_name: {CONTAINER}
    environment:
      VERSION: {version:?}
      LANGUAGE: {language:?}
      CPU_CORES: "{cores}"
      RAM_SIZE: "{ram}G"
      DISK_SIZE: "{disk}G"
      USERNAME: {username:?}
      PASSWORD: {password:?}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8006:8006
      - 127.0.0.1:3389:3389/tcp
      - 127.0.0.1:3389:3389/udp
    volumes:
      - ./storage:/storage
    restart: "no"
    stop_grace_period: 2m
"#
    )
}

fn launcher_script(username: &str, password: &str) -> String {
    // Your home folder shows up in Windows as a drive named "Home".
    format!(
        r#"#!/bin/bash
# Generated by LazyArch: starts the Windows container and connects over RDP.
if [ "$(docker inspect -f '{{{{.State.Running}}}}' {CONTAINER} 2>/dev/null)" != "true" ]; then
    docker start {CONTAINER} || {{ notify-send "Windows" "Could not start the container. Is Docker running and are you in the docker group?"; exit 1; }}
    notify-send "Windows" "Starting Windows..." 2>/dev/null
    sleep 30 # ponytail: fixed boot wait, poll the RDP port if it's often too short
fi
RDP=$(command -v sdl-freerdp3 || command -v xfreerdp3 || command -v xfreerdp)
exec "$RDP" /v:127.0.0.1 /u:{user} /p:{pass} /cert:ignore /dynamic-resolution +clipboard /sound /drive:Home,"$HOME"
"#,
        user = sh_quote(username),
        pass = sh_quote(password),
    )
}

/// Windows in a Docker container (dockurr/windows), opened over RDP like Omarchy does.
pub fn run() {
    if !Path::new("/dev/kvm").exists() {
        ui::warn("KVM is not available. Enable virtualization (Intel VT-x / AMD-V) in your BIOS/UEFI first.");
        return;
    }

    if !docker::done() {
        ui::info("Windows runs in a Docker container, setting up Docker first...");
        docker::run();
    }
    pacman_install(&["freerdp"]);

    let versions = ["11", "10"];
    let version = versions[Select::new()
        .with_prompt("Windows version")
        .items(&["Windows 11", "Windows 10"])
        .default(0)
        .interact()
        .unwrap()];

    let language: String = Input::new()
        .with_prompt("Windows language (e.g. English, Portuguese, Spanish)")
        .default("English".into())
        .interact_text()
        .unwrap();

    let half_cpus = std::thread::available_parallelism().map_or(2, |n| (n.get() / 2).max(1));
    let cores: u32 = Input::new().with_prompt("CPU cores").default(half_cpus as u32).interact_text().unwrap();
    let ram: u32 = Input::new().with_prompt("RAM (GB)").default(4).interact_text().unwrap();
    let disk: u32 = Input::new().with_prompt("Disk size (GB)").default(64).interact_text().unwrap();

    let username: String = Input::new()
        .with_prompt("Windows username")
        .default("lazyarch".into())
        .interact_text()
        .unwrap();
    let password = Password::new()
        .with_prompt("Windows password")
        .with_confirmation("Repeat password", "Passwords don't match")
        .interact()
        .unwrap();

    let dir = dir();
    fs::create_dir_all(&dir).expect("Failed to create Windows directory");

    let compose = compose_yaml(version, &language, cores, ram, disk, &username, &password);
    // The compose file and launcher hold the password: readable by you only.
    let compose_path = dir.join("compose.yml");
    write_private(&compose_path, &compose, 0o600);

    let launcher = launcher_script(&username, &password);
    let launcher_path = dir.join("windows.sh");
    write_private(&launcher_path, &launcher, 0o700);

    let home = std::env::var("HOME").expect("HOME not set");
    let apps_dir = Path::new(&home).join(".local/share/applications");
    fs::create_dir_all(&apps_dir).expect("Failed to create applications directory");
    let desktop = format!(
        "[Desktop Entry]\nType=Application\nName=Windows\nComment=Windows VM (LazyArch)\nExec=\"{}\"\nIcon=computer\nTerminal=false\nCategories=System;\n",
        launcher_path.display()
    );
    fs::write(apps_dir.join("lazyarch-windows.desktop"), desktop).expect("Failed to write desktop entry");

    ui::info("Starting the Windows installer...");
    sudo(&["docker", "compose", "-f", &compose_path.to_string_lossy(), "up", "-d"]);

    ui::success("Windows is installing by itself (big download, 15-30 min).");
    println!("  Watch the progress at: http://127.0.0.1:8006");
    println!("  When it's done, open 'Windows' from your app menu (log out and back in first if Docker was just set up).");
    println!("  Stop it with: docker stop {CONTAINER}");
}

#[cfg(test)]
mod tests {
    use super::*;

    // A password with quotes must not break the YAML or the shell script.
    #[test]
    fn generated_files_escape_quotes() {
        let password = r#"a"b'c\d"#;
        let yaml = compose_yaml("11", "English", 2, 4, 64, "me", password);
        assert!(yaml.contains(r#"PASSWORD: "a\"b'c\\d""#), "{yaml}");
        let script = launcher_script("me", password);
        assert!(script.contains(r#"/p:'a"b'\''c\d'"#), "{script}");
    }
}
